### ISSUE TITLE
Light Toggle creates Strobe effect

### ISSUE THREAD

**Issue by PDXUser** [korapp/plasma-homeassistant#5] opened 2023-09-12 11:55 UTC
I added my first entry after getting the qt5-websockets installed and rebooting.  

The entity is my Desk lamp, and I added the option to Toggle it: 
![image](https://github.com/korapp/plasma-homeassistant/assets/20736534/4498d940-eca0-4387-af08-3e3741d3509b)

After hitting Apply, it turned the light off...paused about 1 second...back on...then off then on then off then on then off then on then went into strobe mode.    Thank you for proving to me that I can somehow strobe my Cost Feit light! :zap:   While this is a great effect for Halloween, I'm afraid it won't work for daily use. :)    

Also, I noticed that If I change the action to Turn On/Turn Off (either way), it overrides my current setting in Home Assistant, for example, Having it set to Turn On, only allowed my light to be set to 6%.   Manually turning it off and on in the Home ASsistant Dashboard, it changed it from 100% to 6% so your app is assuming Master Control by presumably sending a stream of instructions when the action is selected.

**Comment by korapp** [comment] 2023-09-12 20:54
This fatal glitch has already been fixed in the dev branch. Thank you for reporting this.
However, I cannot reproduce the second problem - my RGB strip turns on with the last set color and brightness.
Could you share which version of HA you are using?

**Comment by PDXUser** [comment] 2023-09-12 20:58
![image](https://github.com/korapp/plasma-homeassistant/assets/20736534/f6c5018f-236c-4f50-a3fd-edf19042c379)

I can try to fix my copy if you want by viewing the one you linked and let you know.

**Comment by PDXUser** [comment] 2023-09-12 21:34
Never mind my attempt, it broke things, but I'm patient, I will wait for the next release. :)

**Closed** 2023-09-13 12:08 UTC
